name: Run Python tests
on:
  push:
    branches:
      - fast-api-rewrite

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SQL_URL: "postgres://postgres:postgres@localhost:5432/postgres"
      JWT_SECRET: "secret"
      JWT_ALGORITHM: "HS256"
      MAIL_USERNAME: "hello@reminderse.com"
      MAIL_PASSWORD: "password"
      MAIL_SERVER: "smtp.zoho.com"
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run tests
        run: |
          python3 -m pytest
