name: Run Python tests
on:
  push:
    branches:
      - fast-api-rewrite

jobs:
  - name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Run tests
        run: |
          python3 -m pytest
          python3 -m pytest --cov=. --cov-report=html:coverage.html
          python3 -m pytest --cov=. --cov-report=term --cov-report-junit=junit.xml
